"""
Django settings for african_bamboo_dashboard project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from os import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ.get("DEBUG", False)

ALLOWED_HOSTS = ["*"]


# Application definition

# Default django apps
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Add API apps below
API_APPS = [
    "api.v1.v1_init",
    "api.v1.v1_users",
    "api.v1.v1_odk",
    "api.v1.v1_jobs",
]

# Add third party apps below
EXTERNAL_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_dbml",
    "django_q",
]

INSTALLED_APPS = DJANGO_APPS + API_APPS + EXTERNAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "african_bamboo_dashboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "african_bamboo_dashboard" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "african_bamboo_dashboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": environ.get("DB_SCHEMA"),
        "USER": environ.get("DB_USER"),
        "PASSWORD": environ.get("DB_PASSWORD"),
        "HOST": environ.get("DB_HOST"),
        "PORT": environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST_FRAMEWORK SETTINGS
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.v1.v1_users.auth.StatusAwareJWTAuthentication",
    ],
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DATE_FORMAT": "%d-%m-%Y",
    "DEFAULT_VERSION": "v1",
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination"
    ".LimitOffsetPagination",
    "PAGE_SIZE": 10,
}

# DRF_SPECTACULAR SETTINGS
# https://drf-spectacular.readthedocs.io/en/latest/settings.html

SPECTACULAR_SETTINGS = {
    "TITLE": "african_bamboo_dashboard",
    "DESCRIPTION": "API for african_bamboo_dashboard",
    "VERSION": "1.0.0",
    "SORT_OPERATIONS": False,
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# SIMPLE_JWT SETTINGS
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# MAIL SETUP
EMAIL_BACKEND = "django_mailjet.backends.MailjetBackend"
# Read with .get: a missing mail credential must not stop the
# task worker from importing Django. Sending fails loudly at send
# time instead of crashing qcluster on boot.
MAILJET_API_KEY = environ.get("MAILJET_APIKEY", "")
MAILJET_API_SECRET = environ.get("MAILJET_SECRET", "")
EMAIL_FROM = environ.get("EMAIL_FROM") or "noreply@akvo.org"

# APP SETUP
WEBDOMAIN = environ.get("WEBDOMAIN", "http://localhost:3000")
TEST_ENV = bool(environ.get("TEST_ENV", False))

# CSRF trusted origins — Django admin form POSTs come from the
# frontend proxy host. Without this, Django's Origin check
# rejects the request with 403 "Origin checking failed".
# Guard: Django 4 requires values to start with http:// or
# https://. CI may set WEBDOMAIN to a bare string like "notset".
CSRF_TRUSTED_ORIGINS = (
    [WEBDOMAIN]
    if WEBDOMAIN.startswith(("http://", "https://"))
    else []
)

# Override the default user model
AUTH_USER_MODEL = "v1_users.SystemUser"

# Django Q2 — async task queue backed by PostgreSQL ORM

# NOTE: TEST_ENV is not exported by test.sh or
# docker-compose.test.yml, so this is False during the test run
# and django_q reads Q_CLUSTER once at import — @override_settings
# cannot change it. Tests therefore only ENQUEUE; they must patch
# async_task or call the task function directly.
Q_IS_SYNC = bool(TEST_ENV)

# "retry" is the ORM broker's visibility timeout, so it MUST be
# greater than "timeout" — otherwise a task still running is
# redelivered to another worker and re-run forever. Pinned by
# api/v1/v1_odk/tests/tests_qcluster_settings.py.
Q_CLUSTER = {
    "name": "african_bamboo",
    "workers": 2,
    "timeout": 600,
    "retry": 900,
    "max_attempts": 1,
    "ack_failures": True,
    "orm": "default",
    "sync": Q_IS_SYNC,
}

# In tests, bypass Mailjet so emails land in mail.outbox.
if TEST_ENV:
    EMAIL_BACKEND = (
        "django.core.mail.backends.locmem.EmailBackend"
    )

# LOGGING
# Without this, application loggers have no handler and
# propagate to a bare root logger, so Python's
# lastResort handler drops everything below WARNING --
# INFO diagnostics were silently discarded in
# production. Send them to stdout, which is what the
# container runtime collects.
LOG_LEVEL = environ.get("LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "%(asctime)s %(levelname)s "
                "%(name)s: %(message)s"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "standard",
        },
    },
    "loggers": {
        # Application code. "api" covers the v1 apps,
        # "utils" the Kobo/Telegram/storage clients.
        "api": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "utils": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django_q": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Storage path for file uploads and exports
STORAGE_PATH = environ.get("STORAGE_PATH", "./storage")
STORAGE_SECRET = environ.get(
    "STORAGE_SECRET", SECRET_KEY
)

# Telegram notification settings
# These are fallback defaults; DB settings
# (SystemSetting model) override these at runtime.
TELEGRAM_ENABLED = (
    environ.get("TELEGRAM_ENABLED", "False").lower()
    in ("true", "1", "yes")
)
TELEGRAM_BOT_TOKEN = environ.get(
    "TELEGRAM_BOT_TOKEN", ""
)
TELEGRAM_SUPERVISOR_GROUP_ID = environ.get(
    "TELEGRAM_SUPERVISOR_GROUP_ID", ""
)
TELEGRAM_ENUMERATOR_GROUP_ID = environ.get(
    "TELEGRAM_ENUMERATOR_GROUP_ID", ""
)
