# Generated by Django 4.2.28 on 2026-02-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="kobo_password",
            field=models.TextField(
                blank=True,
                help_text="Encrypted KoboToolbox password",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="kobo_url",
            field=models.URLField(
                blank=True,
                help_text="KoboToolbox server URL",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="kobo_username",
            field=models.CharField(
                blank=True,
                help_text="KoboToolbox username",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
