# Generated by Django 4.2.28 on 2026-03-02 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "export_shapefile"), (2, "export_geojson")]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "on_progress"),
                            (3, "failed"),
                            (4, "done"),
                        ],
                        default=1,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("result", models.TextField(default=None, null=True)),
                ("info", models.JSONField(default=None, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("available", models.DateTimeField(default=None, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jobs",
            },
        ),
    ]
