# Generated by Django 4.2.28 on 2026-03-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "export_shapefile"), (2, "export_geojson")]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "on_progress"),
                            (3, "failed"),
                            (4, "done"),
                        ],
                        default=1,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("result", models.TextField(default=None, null=True)),
                ("info", models.JSONField(default=None, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("available", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "jobs",
            },
        ),
    ]
