# Generated by Django 4.2.28 on 2026-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "export_shapefile"),
                    (2, "export_geojson"),
                    (3, "export_xlsx"),
                ]
            ),
        ),
    ]
