# Generated by Django 4.2.28 on 2026-02-16 03:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_uid",
                    models.CharField(
                        db_index=True, max_length=255, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="Form display name",
                        max_length=500,
                    ),
                ),
                (
                    "last_sync_timestamp",
                    models.BigIntegerField(
                        default=0, help_text="Epoch ms of last successful sync"
                    ),
                ),
                (
                    "polygon_field",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated field paths for polygon in ODK geoshape format. First non-empty match is used.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "region_field",
                    models.CharField(
                        blank=True,
                        help_text="Name of the field in the form that captures region",
                        max_length=125,
                        null=True,
                    ),
                ),
                (
                    "sub_region_field",
                    models.CharField(
                        blank=True,
                        help_text="Name of the field in the form that captures sub-region",
                        max_length=125,
                        null=True,
                    ),
                ),
                (
                    "plot_name_field",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated field names for plot name. Values joined with spaces.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "form metadata",
                "db_table": "form_metadata",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True, max_length=255, unique=True
                    ),
                ),
                ("kobo_id", models.CharField(max_length=255)),
                (
                    "submission_time",
                    models.BigIntegerField(db_index=True, help_text="Epoch ms"),
                ),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instance_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(help_text="Full dynamic form JSON"),
                ),
                (
                    "system_data",
                    models.JSONField(
                        blank=True,
                        help_text="_geolocation, _tags, etc.",
                        null=True,
                    ),
                ),
                (
                    "approval_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Approved"), (2, "Not approved")],
                        db_index=True,
                        help_text="NULL means pending",
                        null=True,
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from reviewer on approval or rejection",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="v1_odk.formmetadata",
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-submission_time"],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "plot_name",
                    models.CharField(
                        help_text="Farmer full name", max_length=500
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "polygon_wkt",
                    models.TextField(
                        blank=True, help_text="Polygon in WKT format", null=True
                    ),
                ),
                (
                    "min_lat",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "max_lat",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "min_lon",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "max_lon",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                ("region", models.CharField(max_length=255)),
                ("sub_region", models.CharField(max_length=255)),
                ("created_at", models.BigIntegerField(help_text="Epoch ms")),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="v1_odk.formmetadata",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plot",
                        to="v1_odk.submission",
                    ),
                ),
            ],
            options={
                "db_table": "plots",
            },
        ),
    ]
