# Generated by Django 4.2.28 on 2026-02-12 03:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormMetadata",
            fields=[
                (
                    "asset_uid",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="Form display name",
                        max_length=500,
                    ),
                ),
                (
                    "last_sync_timestamp",
                    models.BigIntegerField(
                        default=0, help_text="Epoch ms of last successful sync"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "form metadata",
                "db_table": "form_metadata",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("kobo_id", models.CharField(max_length=255)),
                (
                    "submission_time",
                    models.BigIntegerField(
                        db_index=True, help_text="Epoch ms"
                    ),
                ),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instance_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(help_text="Full dynamic form JSON"),
                ),
                (
                    "system_data",
                    models.JSONField(
                        blank=True,
                        help_text="_geolocation, _tags, etc.",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        db_column="asset_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="v1_odk.formmetadata",
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-submission_time"],
            },
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "uuid",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plot_name",
                    models.CharField(
                        help_text="Farmer full name", max_length=500
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "polygon_wkt",
                    models.TextField(help_text="Polygon in WKT format"),
                ),
                ("min_lat", models.FloatField(db_index=True)),
                ("max_lat", models.FloatField(db_index=True)),
                ("min_lon", models.FloatField(db_index=True)),
                ("max_lon", models.FloatField(db_index=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("form_id", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("sub_region", models.CharField(max_length=255)),
                ("created_at", models.BigIntegerField(help_text="Epoch ms")),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        db_column="submission_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plot",
                        to="v1_odk.submission",
                    ),
                ),
            ],
            options={
                "db_table": "plots",
            },
        ),
    ]
