# Generated by Django 4.2.28 on 2026-02-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique question name within the form",
                        max_length=125,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Question label shown to users",
                        max_length=500,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Question type, e.g. text, integer, select_one etc.",
                        max_length=125,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="v1_odk.formmetadata",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "form questions",
                "db_table": "form_questions",
                "unique_together": {("form", "name")},
            },
        ),
        migrations.CreateModel(
            name="FormOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Option value stored in submission",
                        max_length=125,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Option label shown to users", max_length=500
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="v1_odk.formquestion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "form options",
                "db_table": "form_options",
            },
        ),
    ]
