# Generated by Django 4.2.28 on 2026-02-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0002_formquestion_formoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formmetadata",
            name="region_field",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated field names for region. Non-empty values joined with ' - '.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formmetadata",
            name="sub_region_field",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated field names for sub-region. Non-empty values joined with ' - '.",
                max_length=255,
                null=True,
            ),
        ),
    ]
