# Generated by Django 4.2.28 on 2026-02-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0003_alter_region_sub_region_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="flagged_for_review",
            field=models.BooleanField(
                default=None,
                help_text=(
                    "NULL = not yet checked, "
                    "False = checked and clean, True = flagged for review."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="flagged_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for flagging the plot for review",
                max_length=500,
                null=True,
            ),
        ),
    ]
