# Generated by Django 4.2.28 on 2026-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0004_plot_flagged_for_review_plot_flagged_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="instance_name",
        ),
        migrations.AddField(
            model_name="plot",
            name="polygon_source_field",
            field=models.CharField(
                blank=True,
                help_text="Which polygon_field the geometry was read from during extraction.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="plot_name",
            field=models.CharField(
                blank=True, help_text="Farmer full name", max_length=500, null=True
            ),
        ),
    ]
