# Generated by Django 4.2.28 on 2026-03-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1_odk", "0005_remove_plot_instance_name_plot_polygon_source_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="reviewer_notes",
        ),
        migrations.CreateModel(
            name="RejectionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("polygon_error", "Polygon Error"),
                            ("overlap", "Overlap"),
                            ("duplicate", "Duplicate Submission"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason_text", models.TextField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(auto_now_add=True)),
                ("sync_status", models.CharField(default="pending", max_length=20)),
                ("kobo_response", models.JSONField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_sync_attempt", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("telegram_sent_at", models.DateTimeField(blank=True, null=True)),
                ("telegram_chat_ids", models.JSONField(blank=True, null=True)),
                (
                    "telegram_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejection_audits",
                        to="v1_odk.plot",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejection_audits",
                        to="v1_odk.submission",
                    ),
                ),
                (
                    "validator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejection_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rejection_audits",
                "ordering": ["-rejected_at"],
            },
        ),
    ]
