# Generated by Django 4.2.28 on 2026-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0006_remove_submission_reviewer_notes_rejectionaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="formmetadata",
            name="filter_fields",
            field=models.JSONField(
                blank=True,
                help_text="List of field names from raw_data to use as filter dropdowns. Only select_one/select_multiple types are supported.",
                null=True,
            ),
        ),
    ]
