# Generated by Django 4.2.28 on 2026-03-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1_odk", "0007_formmetadata_filter_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Standardized field name", max_length=125, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "field settings",
                "db_table": "field_settings",
            },
        ),
        migrations.AddField(
            model_name="plot",
            name="area_ha",
            field=models.FloatField(
                blank=True, help_text="Pre-computed area in hectares", null=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last validator action", null=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Last validator who acted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="v1_odk.fieldsettings",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="v1_odk.formmetadata",
                    ),
                ),
                (
                    "form_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="v1_odk.formquestion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "field mappings",
                "db_table": "field_mappings",
                "unique_together": {("field", "form")},
            },
        ),
    ]
