# Generated by Django 4.2.28 on 2026-03-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0008_fieldsettings_plot_area_ha_submission_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("form", "kobo_id")},
        ),
    ]
