# Generated by Django 4.2.28 on 2026-03-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0010_alter_flagged_reason_to_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=125, unique=True)),
                (
                    "lookup_key",
                    models.CharField(
                        db_index=True,
                        help_text="Concatenated unique_fields values joined with ' - ' for deduplication",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        help_text="Key-value pairs of standardized field name to value",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "farmers",
            },
        ),
        migrations.CreateModel(
            name="FarmerFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_fields",
                    models.TextField(
                        help_text="Comma-separated standardized field names used to identify unique farmers. Values joined with ' - ' for display."
                    ),
                ),
                (
                    "values_fields",
                    models.TextField(
                        help_text="Comma-separated standardized field names to store as key-value pairs in Farmer.values. First field is used as display name."
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_field_mapping",
                        to="v1_odk.formmetadata",
                    ),
                ),
            ],
            options={
                "db_table": "farmer_field_mapping",
            },
        ),
        migrations.AddField(
            model_name="plot",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plots",
                to="v1_odk.farmer",
            ),
        ),
    ]
