# Generated by Django 4.2.28 on 2026-03-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0011_farmer_farmerfieldmapping_plot_farmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="formmetadata",
            name="sortable_fields",
            field=models.JSONField(
                blank=True,
                help_text="List of raw_data field names that can be used for sorting in the submissions table.",
                null=True,
            ),
        ),
    ]
