# Generated by Django 4.2.28 on 2026-03-31 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0013_farmerfieldmapping_uid_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="formmetadata",
            name="plot_uid_start",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum starting UID number for plots. New plot UIDs will be max(max_existing + 1, plot_uid_start). Use this to continue numbering from a legacy system (e.g., 351 to continue after PLT00350).",
            ),
        ),
        migrations.CreateModel(
            name="MainPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_plots",
                        to="v1_odk.formmetadata",
                    ),
                ),
            ],
            options={
                "db_table": "main_plots",
            },
        ),
        migrations.CreateModel(
            name="MainPlotSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="v1_odk.mainplot",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_plot_submissions",
                        to="v1_odk.submission",
                    ),
                ),
            ],
            options={
                "db_table": "main_plot_submissions",
                "unique_together": {("main_plot", "submission")},
            },
        ),
    ]
