# Generated by Django 4.2.28 on 2026-09-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0014_mainplotsubmission_onetoone"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionaudit",
            name="telegram_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rejectionaudit",
            name="telegram_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rejectionaudit",
            name="telegram_last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rejectionaudit",
            name="telegram_next_attempt_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="missing_from_kobo_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set by sync when KoboToolbox no longer returns this submission. Such a row can never sync again — every validation-status update answers 400 'submission ids are invalid' — so approve/reject are blocked and only deletion is offered.",
                null=True,
            ),
        ),
    ]
