# Generated by Django 4.2.28 on 2026-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0015_telegram_delivery_ledger_and_stale_submissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("form", "kobo_id")},
        ),
        migrations.AlterField(
            model_name="submission",
            name="uuid",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("form", "kobo_id"), ("form", "uuid")},
        ),
    ]
