# Generated by Django 4.2.28 on 2026-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1_odk", "0016_submission_uuid_unique_per_form"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("form", "kobo_id")},
        ),
    ]
